/**
 * Q14: curated English↔Spanish aliases for the built-in library, keyed by
 * exercise id. These short/common forms make search and duplicate detection
 * work across languages ("bench press" finds Press Banca Barra and back).
 * Matching is always normalized (case/accents/punctuation-insensitive).
 */
export const EXERCISE_ALIASES: Record<string, string[]> = {
    bp_bar: ['bench press', 'press banca', 'press de banca', 'flat bench press', 'press plano'],
    bp_inc_bar: ['incline bench press', 'press inclinado', 'press inclinado con barra'],
    bp_flat: ['press pecho', 'chest press machine'],
    bp_paused: ['press banca con pausa', 'paused bench'],
    pushup: ['push up', 'pushups', 'flexiones de brazos', 'lagartijas', 'push-up'],
    diamond_pushup: ['flexiones diamante cerradas', 'close grip pushup'],
    pullup: ['pull up', 'pullups', 'dominada', 'dominadas estrictas'],
    chinup: ['chin up', 'chinups', 'dominada supina', 'dominadas agarre supino'],
    lat_pull: ['pulldown', 'lat pull down', 'jalon al pecho en polea', 'jalon'],
    row_cable: ['seated cable row', 'remo sentado', 'remo polea baja'],
    row_db: ['one arm row', 'remo a una mano', 'remo unilateral', 'remo con mancuerna'],
    row_mach: ['remo hammer', 'machine rows'],
    pendlay_row: ['remo pendlay con barra'],
    sq_bar: ['squat', 'sentadilla', 'sentadilla libre', 'back squat', 'sentadilla trasera'],
    front_squat: ['front squats', 'sentadilla frontal con barra'],
    sq_hack: ['hack squats', 'maquina hack'],
    leg_ext: ['leg extensions', 'extension de cuadriceps', 'sillon de cuadriceps', 'camilla de cuadriceps'],
    leg_curl: ['leg curls', 'curl femoral', 'hamstring curl', 'camilla femoral'],
    lying_curl: ['lying curl', 'curl femoral acostado'],
    leg_press: ['press de piernas', 'prensa', 'prensa de piernas 45'],
    single_leg_press: ['prensa unilateral'],
    lunges: ['lunge', 'zancada', 'estocada', 'desplante'],
    bulgarian_split_squat: ['bulgarian squat', 'sentadilla a una pierna', 'desplante bulgaro'],
    deadlift: ['deadlifts', 'peso muerto', 'despegue', 'levantamiento de peso muerto'],
    rdl: ['rdl', 'rumanian deadlift', 'peso muerto rumano con barra'],
    sldl: ['stiff legged deadlift', 'peso muerto piernas rectas'],
    good_morning: ['buenos dias con barra'],
    ohp: ['overhead presses', 'press militar con barra', 'military press', 'shoulder press', 'press de hombros'],
    ohp_db: ['press militar sentado', 'seated shoulder press'],
    lat_raise: ['lateral raises', 'vuelos laterales', 'elevaciones', 'vuelos'],
    rear_delt_fly: ['pajaros', 'reverse fly', 'aperturas posteriores'],
    face_pull: ['face pulls', 'jalon a la cara'],
    shrug_db: ['shrugs', 'encogimientos', 'trapecio con mancuernas'],
    curl_bar: ['barbell curls', 'curl de biceps', 'curl biceps barra'],
    curl_db: ['dumbbell curls', 'curl alternado', 'curl con mancuernas alternado'],
    curl_hammer: ['hammer curls', 'curl neutro', 'curl martillo alternado'],
    curl_ez: ['curl barra romana'],
    curl_cable: ['curl polea baja'],
    curl_preacher: ['predicador'],
    tri_push: ['pushdown', 'triceps polea', 'jalon de triceps', 'extension polea'],
    rope_pressdown: ['pressdown con cuerda', 'triceps soga'],
    skull_crusher: ['skullcrushers', 'press frances', 'rompecraneos', 'french press'],
    tri_ext: ['overhead triceps', 'triceps sobre cabeza'],
    db_tri_ext: ['triceps mancuerna una mano'],
    jm_press: ['press jm barra'],
    dips: ['dip', 'fondos', 'fondos en paralelas'],
    dip_machine: ['fondos en maquina'],
    cable_crossover: ['cruces de polea', 'cruce polea', 'cruces'],
    db_fly: ['aperturas planas', 'flyes'],
    calf_raise: ['calf raises', 'gemelos', 'elevacion de gemelos', 'pantorrilla'],
    leg_raise: ['hanging leg raises', 'abdominales colgado', 'elevacion de piernas colgado'],
    abs_cable: ['crunch polea alta', 'abdominales en polea'],
    cardio_run: ['correr', 'running'],
    cardio_row: ['remoergometro', 'ergometro'],
    farmers_walk: ['paseo granjero', 'caminata granjero'],
};
