export const KONG_SUBSTITUTION_GROUPS: Record<string, string[]> = {
  triceps_extension: ['tri_push', 'rope_pressdown', 'skull_crusher', 'db_tri_ext', 'tri_ext', 'db_overhead_tri'],
  biceps_curl: ['curl_bar', 'curl_db', 'curl_hammer', 'curl_cable', 'curl_preacher', 'incline_db_curl', 'close_grip_cable_curl', 'rope_cable_curl'],
  front_delt_raise: ['front_raise_db', 'ohp_db'],
  upright_row: ['upright_row', 'shrug_db', 'face_pull'],
  incline_press: ['bp_inc_bar', 'bp_inc', 'bp_inc_wide'],
  machine_chest_press: ['bp_flat', 'bp_mach_inc'],
  chest_fly: ['pec_fly', 'db_fly', 'cable_crossover'],
  hamstring_knee_flexion: ['leg_curl', 'lying_curl'],
  leg_press: ['leg_press', 'single_leg_press'],
  hip_hinge: ['rdl', 'sldl', 'deadlift', 'good_morning', 'good_morning_pause'],
  lunge: ['lunges', 'lunge_reverse', 'step_up_db'],
  leg_extension: ['leg_ext', 'single_leg_extension'],
  horizontal_row: ['row_cable', 'row_db', 'row_mach', 'high_machine_row', 'wide_grip_cable_row', 'bent_barbell_row'],
  vertical_pull: ['lat_pull', 'lat_pull_supine', 'one_arm_lat_pulldown', 'close_grip_lat_pulldown', 'behind_neck_pulldown', 'chinup'],
  squat: ['sq_bar', 'sq_paused', 'high_bar_close_squat', 'front_squat', 'low_bar_wide_squat'],
  back_extension: ['back_extension', 'good_morning', 'good_morning_pause'],
  military_press: ['ohp', 'ohp_db', 'push_press', 'behind_neck_press'],
  lateral_raise: ['lat_raise', 'lat_raise_cable', 'lat_raise_mach', 'lat_raise_seat'],
  dip: ['dips', 'dip_machine'],
  stiff_leg_deadlift: ['sldl', 'rdl', 'good_morning'],
  split_squat: ['bulgarian_split_squat', 'lunges', 'lunge_reverse'],
  close_grip_press: ['close_grip_bench', 'close_grip_floor_press', 'bp_bar'],
  hack_squat: ['sq_hack', 'leg_press'],
  pullover: ['pullover_db', 'lat_prayer'],
  push_press: ['push_press', 'ohp'],
  elevated_deadlift: ['deadlift_13in', 'rack_pull', 'deadlift'],
  pendlay_row: ['pendlay_row', 'bent_barbell_row', 'row_db'],
  good_morning: ['good_morning', 'good_morning_pause', 'rdl'],
  tbar_row: ['tbar_row_chest_supported', 'row_mach', 'row_cable'],
  wide_bench_press: ['wide_bench_press', 'bp_bar', 'bp_inc_wide'],
  floor_press: ['close_grip_floor_press', 'bp_bar'],
  neutral_db_press: ['neutral_db_press', 'bp_inc', 'ohp_db'],
  wide_stance_squat: ['low_bar_wide_squat', 'sq_bar', 'sq_hack'],
  front_squat: ['front_squat', 'sq_bar', 'high_bar_close_squat'],
  chinup: ['chinup', 'pullup', 'lat_pull_supine'],
};
