import type { LocalizedText } from '../types';

export interface KongGuideSection { id: string; title: LocalizedText; summary: LocalizedText; }

export const KONG_GUIDE: KongGuideSection[] = [
  { id: 'what-is-kong', title: { en: 'What is KONG?', es: 'Qué es KONG' }, summary: { en: 'A deliberately anti-specialization hypertrophy/powerbuilding system. Variety, volume, density and fatigue build capacity before heavier expression.', es: 'Un sistema de hipertrofia/powerbuilding deliberadamente anti-especialización. Variedad, volumen, densidad y fatiga construyen capacidad antes de expresar más fuerza.' } },
  { id: 'variety', title: { en: 'Overspecialization / Variety', es: 'Especialización / Variedad' }, summary: { en: 'Variety is structured, not random: stay with a method long enough to adapt, then rotate before monotony and weak points stall progress.', es: 'La variedad es estructurada, no aleatoria: mantén un método el tiempo suficiente para adaptarte y cambia antes de que la monotonía y los puntos débiles frenen el progreso.' } },
  { id: 'weak-points', title: { en: 'Tenet 1 — Weak Points First', es: 'Principio 1 — Puntos débiles primero' }, summary: { en: 'Block 1 places smaller work before compounds. Your usual loads may drop; you are not testing fresh strength.', es: 'Block 1 coloca el trabajo pequeño antes de los compounds. Es normal usar menos carga: no estás probando fuerza fresca.' } },
  { id: 'density', title: { en: 'Tenet 2 — Density', es: 'Principio 2 — Densidad' }, summary: { en: 'Density is work per unit of time. Block 1 recommends roughly one minute between exercises; take longer if fatigue demands it.', es: 'Densidad es trabajo por unidad de tiempo. Block 1 recomienda aproximadamente un minuto entre ejercicios; descansa más si la fatiga lo exige.' } },
  { id: 'volume', title: { en: 'Tenet 3 — Volume', es: 'Principio 3 — Volumen' }, summary: { en: 'Volume rises progressively so capacity can adapt. Do not attack week four volume on week one.', es: 'El volumen sube progresivamente para que la capacidad se adapte. No intentes hacer el volumen de la semana cuatro en la primera.' } },
  { id: 'high-reps', title: { en: 'Tenet 4 — High Reps with Compounds', es: 'Principio 4 — Altas reps con compounds' }, summary: { en: 'Big movements also live in high rep ranges and fatigue; the goal is repeating quality efforts, not only one heavy rep.', es: 'Los movimientos grandes también usan rangos altos y fatiga: el objetivo es repetir esfuerzos de calidad, no solo una repetición pesada.' } },
  { id: 'fatigued-strength', title: { en: 'Tenet 5 — Fatigued Strength', es: 'Principio 5 — Fuerza fatigada' }, summary: { en: 'In Block 2, 12/10/8 are working sets, not warmups. The top set is intentionally lower than a fresh top set.', es: 'En Block 2, 12/10/8 son series de trabajo, no calentamientos. El top set es intencionalmente menor que uno fresco.' } },
  { id: 'load-variation', title: { en: 'Tenet 6 — Load Variation', es: 'Principio 6 — Variación de carga' }, summary: { en: 'Pyramids and reverse pyramids expose multiple thresholds and reduce monotony by changing reps and load set to set.', es: 'Las pirámides y reverse pyramids exponen varios umbrales y reducen la monotonía cambiando reps y carga de serie a serie.' } },
  { id: 'phase-potentiation', title: { en: 'Tenet 7 — Phase Potentiation', es: 'Principio 7 — Potenciación por fases' }, summary: { en: 'Capacity and weak points prepare fatigued compounds, which prepare fresh overload top sets and high-rep backoffs.', es: 'La capacidad y los puntos débiles preparan compounds fatigados, que preparan top sets frescos y backoffs de altas reps.' } },
  { id: 'rpe', title: { en: 'RPE in KONG', es: 'RPE en KONG' }, summary: { en: 'RPE is a guide, not a math exam. Start each block conservatively, leave room to progress, and become more assertive late in the block.', es: 'El RPE guía, no es un examen matemático. Empieza cada bloque conservador, deja margen para progresar y sé más agresivo al final.' } },
  { id: 'recovery', title: { en: 'Recovery', es: 'Recuperación' }, summary: { en: 'Prioritize recovering between sessions, managing DOMS and tolerating work without irritating joints or connective tissue.', es: 'Prioriza recuperarte entre sesiones, manejar el DOMS y tolerar el trabajo sin irritar articulaciones o tejido conectivo.' } },
  { id: 'nutrition', title: { en: 'Nutrition', es: 'Nutrición' }, summary: { en: 'Eat enough to support high volume. KONG does not prescribe macros; use GainsLab Diet according to your goals.', es: 'Come lo suficiente para sostener el volumen alto. KONG no prescribe macros; usa la Dieta de GainsLab según tus objetivos.' } },
];
