import React from 'react';
import type { Log, MesoCycle } from '../../types';
import { KONG_4DAY_V1 } from '../../programs/kong/kong4Day';
import { getProgramBlockForWeek } from '../../programs/engine/ProgramResolver';
import { calculateProgramMetrics } from '../../programs/engine/ProgramMetrics';

export const ProgramHub: React.FC<{ meso: MesoCycle; logs: Log[]; onClose: () => void; lang: 'en' | 'es' }> = ({ meso, logs, onClose, lang }) => {
  const { block, blockWeek } = getProgramBlockForWeek(KONG_4DAY_V1, meso.week);
  const metrics = calculateProgramMetrics(logs, meso.id, Math.max(1, meso.week * 4), meso.programSystem?.startedBodyWeight);
  const metricCards: Array<[string, string]> = [['sessionsCompleted', lang === 'es' ? 'Sesiones' : 'Sessions'], ['weeksCompleted', lang === 'es' ? 'Semanas' : 'Weeks'], ['setsCompleted', lang === 'es' ? 'Series' : 'Sets'], ['totalVolume', lang === 'es' ? 'Volumen' : 'Volume'], ['totalSeconds', lang === 'es' ? 'Tiempo (min)' : 'Time (min)'], ['averageDensity', lang === 'es' ? 'Densidad (series/min)' : 'Density (sets/min)'], ['adherence', lang === 'es' ? 'Adherencia' : 'Adherence']];
  return <div className="fixed inset-0 z-modal overflow-y-auto bg-[#0b0b0d] p-5 text-white"><div className="mx-auto max-w-xl"><button onClick={onClose} className="min-h-11 text-sm font-bold text-zinc-400">← {lang === 'es' ? 'Cerrar' : 'Close'}</button><div className="mt-5 rounded-3xl border border-primary-500/30 bg-primary-500/10 p-6"><p className="text-xs font-black uppercase tracking-[0.2em] text-primary-400">KONG · Block {block.number}</p><h1 className="mt-2 text-3xl font-black">{lang === 'es' ? `Semana ${meso.week} / 12` : `Week ${meso.week} / 12`}</h1><p className="mt-1 text-sm text-zinc-400">{block.name[lang]} · {lang === 'es' ? `Semana ${blockWeek} / 4` : `Block week ${blockWeek} / 4`}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-zinc-800"><div className="h-full rounded-full bg-primary-500" style={{ width: `${(meso.week / 12) * 100}%` }} /></div></div><div className="mt-5 grid grid-cols-2 gap-3">{metricCards.map(([key, label]) => <div key={key} className="rounded-2xl border border-white/10 bg-zinc-900 p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 text-xl font-black">{key === 'adherence' ? `${Math.round(metrics.adherence * 100)}%` : key === 'totalSeconds' ? Math.round(metrics.totalSeconds / 60) : Math.round(Number(metrics[key as keyof typeof metrics]) || 0)}</p></div>)}</div><div className="mt-4 rounded-2xl border border-white/10 bg-zinc-900 p-4 text-sm text-zinc-400">{metrics.initialBodyWeight || metrics.currentBodyWeight ? `${lang === 'es' ? 'Peso corporal' : 'Body weight'}: ${metrics.initialBodyWeight ?? '—'} → ${metrics.currentBodyWeight ?? '—'}` : (lang === 'es' ? 'Peso corporal: sin datos' : 'Body weight: no data')}</div><div className="mt-5 space-y-2"><p className="text-xs font-black uppercase tracking-widest text-zinc-500">{lang === 'es' ? 'Accesos' : 'Access'}</p>{['Cómo funciona este bloque', 'Los 7 principios', 'RPE en KONG', 'Sustituciones', 'Ver programa completo', 'Mi progreso'].map((item) => <button key={item} className="flex min-h-12 w-full items-center justify-between rounded-2xl border border-white/10 bg-zinc-900 px-4 text-left text-sm font-bold">{item}<span className="text-zinc-500">›</span></button>)}</div></div></div>;
};
